// scripts/extract/extractor.ts
import * as fs from 'fs';
import * as path from 'path';

const MIN_LENGTH = 80;
const MAX_LENGTH = 300;

const GENERATED_PATTERNS = [
  /DO NOT EDIT/i,
  /generated by/i,
  /autogenerated/i,
  /@generated/i,
];

const LICENSE_BLOCK_START = /\/\*[\s\S]*?License[\s\S]*?\*\//i;

interface CandidateSnippet {
  content: string;
  file: string;
  startLine: number;
}

export function isValidSnippet(content: string): boolean {
  if (content.length < MIN_LENGTH || content.length > MAX_LENGTH) {
    return false;
  }
  
  for (const pattern of GENERATED_PATTERNS) {
    if (pattern.test(content)) {
      return false;
    }
  }
  
  if (LICENSE_BLOCK_START.test(content)) {
    return false;
  }
  
  if (content.includes('\u0000')) {
    return false;
  }
  
  const lines = content.split('\n');
  for (const line of lines) {
    if (/^\s*$/.test(line)) continue;
    if (line.trim().length === 0 && lines.filter(l => l.trim().length > 0).length === 0) {
      return false;
    }
  }
  
  return true;
}

export function extractSnippetsFromFile(filePath: string): CandidateSnippet[] {
  const snippets: CandidateSnippet[] = [];
  
  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    const lines = content.split('\n');
    
    let window: string[] = [];
    let startLine = 0;
    
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      
      window.push(line);
      const windowContent = window.join('\n');
      
      if (windowContent.length >= MIN_LENGTH) {
        if (isValidSnippet(windowContent)) {
          snippets.push({
            content: windowContent.trim(),
            file: filePath,
            startLine: startLine + 1,
          });
        }
      }
      
      while (window.join('\n').length > MAX_LENGTH && window.length > 1) {
        window.shift();
        startLine++;
      }
    }
  } catch (error) {
    // Skip files that can't be read
  }
  
  return snippets;
}

export function walkDirectory(dir: string, extensions: string[]): string[] {
  const files: string[] = [];
  
  function walk(currentDir: string) {
    const entries = fs.readdirSync(currentDir, { withFileTypes: true });
    
    for (const entry of entries) {
      const fullPath = path.join(currentDir, entry.name);
      
      if (entry.isDirectory()) {
        if (entry.name.startsWith('.') || entry.name === 'node_modules' || entry.name === 'test' || entry.name === 'tests') {
          continue;
        }
        walk(fullPath);
      } else if (entry.isFile()) {
        const ext = path.extname(entry.name).slice(1);
        if (extensions.includes(ext)) {
          files.push(fullPath);
        }
      }
    }
  }
  
  walk(dir);
  return files;
}
